### ISSUE TITLE
Can this lib be used for any other purpose?

### ISSUE THREAD

**Issue by pingothedoer** [klinker41/android-chips#29] opened 2015-11-03 13:00 UTC
Other than email and contact, suppose i have some options ( probably a list having an option) and a layout where i will show the chosen ones from the list, is that possible?

**Comment by klinker24** [comment] 2016-10-27 20:48
Duplicate of: https://github.com/klinker41/android-chips/issues/26

**Closed by klinker24** 2016-10-27 20:48 UTC
Labels: duplicate
