### ISSUE TITLE
Contacts autocompletion failed for some contacts.

### ISSUE THREAD

**Issue by kunal5692** [klinker41/android-chips#33] opened 2016-01-23 09:25 UTC
I have used this library for one of my application. But there are two issues which i have noticed.
1) Not all the contacts pops in pop up list view. 
2) When i tried to delete chips, only the drawable gets deleted but it still shows the contact number.

**Comment by kpanayotova** [comment] 2016-04-18 20:10
Regarding 1) - I experienced the same issue on some phones. I was using the QUERY_TYPE_PHONE adapter type and it turned out that by default, the adapter only queries for phone numbers marked as "mobile". It took a while to notice because some phones seem to ignore the filter and return all kinds of phone numbers. 

Anyhow, `adapter.setShowMobileOnly(false);` solved the problem for me.

**Comment by mayank26saxena** [comment] 2016-06-29 17:01
Thanks! This saved me a lot of time! :smiley:

**Comment by KtodaZ** [comment] 2016-06-29 20:52
Thanks for that kpanayotova!

**Comment by klinker24** [comment] 2016-10-27 18:55
This is the expected behavior for #2, it allows you to edit the contact number.

**Closed by klinker24** 2016-10-27 18:55 UTC
